export interface StaticProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  category: string;
  subcategory: string;
  image: string;
  inStock: boolean;
  isFeatured: boolean;
  views: number;
  createdAt: string;
  updatedAt: string;
}

export const STATIC_PRODUCTS: StaticProduct[] = [
  // ===== BODY & BEAUTY — Body Mist =====
  {
    id: "dark-kiss-body-mist",
    name: "Dark Kiss Body Mist",
    slug: "dark-kiss-body-mist",
    description: "A mysterious, sensual mist that captures the essence of midnight romance. Dark florals with a hint of amber and musk.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/dark-kiss-body-mist.png",
    inStock: true,
    isFeatured: true,
    views: 310,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "into-the-night-body-mist",
    name: "Into The Night Body Mist",
    slug: "into-the-night-body-mist",
    description: "A golden shimmer mist for the woman who owns the night. Warm amber and vanilla wrapped in glittering dust.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/into-the-night-body-mist.png",
    inStock: true,
    isFeatured: true,
    views: 290,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "kayali-vanilla-28-body-mist",
    name: "Kayali Vanilla 28 Body Mist",
    slug: "kayali-vanilla-28-body-mist",
    description: "Inspired by the iconic scent, a warm vanilla dream with rich gourmand notes. Pure sweetness in a bottle.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/kayali-vanilla-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 180,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "yara-candy-body-mist",
    name: "Yara Candy Body Mist",
    slug: "yara-candy-body-mist",
    description: "Playfully feminine and irresistibly sweet. Fruity candy notes with a fresh floral heart.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/yara-candy-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 215,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "baccarat-rouge-body-mist",
    name: "Baccarat Rouge Body Mist",
    slug: "baccarat-rouge-body-mist",
    description: "Inspired by the legendary Baccarat Rouge 540. A luminous, woody, saffron-tinted haze that leaves a statement.",
    price: 60,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/baccarat-rouge-body-mist.png",
    inStock: true,
    isFeatured: true,
    views: 420,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "in-the-stars-body-mist",
    name: "In The Stars Body Mist",
    slug: "in-the-stars-body-mist",
    description: "Sparkling and celestial. A warm musk blended with notes of peony and sandalwood. Glitter-infused magic.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/in-the-stars-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 175,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "khomra-body-mist",
    name: "Khomra Body Mist",
    slug: "khomra-body-mist",
    description: "A rich oriental mist inspired by tradition. Deep oud, warm spices, and a golden amber trail.",
    price: 60,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/khomra-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 160,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "gingham-body-mist",
    name: "Gingham Body Mist",
    slug: "gingham-body-mist",
    description: "Fresh, clean, and effortlessly beautiful. A light floral body mist that's perfect for everyday elegance.",
    price: 50,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/gingham-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 195,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "angel-pink-body-mist",
    name: "Angel Pink Body Mist",
    slug: "angel-pink-body-mist",
    description: "Soft, romantic, and airy. A sweet peony and delicate candy scent.",
    price: 55,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/angel-pink-body-mist.png",
    inStock: true,
    isFeatured: true,
    views: 260,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "bunny-kiss-body-mist",
    name: "Bunny Kiss Body Mist",
    slug: "bunny-kiss-body-mist",
    description: "Sweet strawberry marshmallows and soft floral musk.",
    price: 50,
    category: "body-beauty",
    subcategory: "Body Mist",
    image: "/images/products/bunny-kiss-body-mist.png",
    inStock: true,
    isFeatured: false,
    views: 140,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ===== BODY & BEAUTY — Perfume Oil =====
  {
    id: "scandal-perfume-oil",
    name: "Scandal Perfume Oil",
    slug: "scandal-perfume-oil",
    description: "Bold, daring, and unforgettable. A vibrant fruity floral that makes every entrance a statement.",
    price: 35,
    category: "body-beauty",
    subcategory: "Perfume Oil",
    image: "/images/products/scandal-perfume-oil.png",
    inStock: true,
    isFeatured: true,
    views: 340,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "thousand-wishes-perfume-oil",
    name: "Thousand Wishes Perfume Oil",
    slug: "thousand-wishes-perfume-oil",
    description: "Warm, sparkling, and full of dreams. Almond blossom, golden peach, and cozy sandalwood.",
    price: 35,
    category: "body-beauty",
    subcategory: "Perfume Oil",
    image: "/images/products/thousand-wishes-perfume-oil.png",
    inStock: true,
    isFeatured: false,
    views: 210,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "dark-kiss-perfume-oil",
    name: "Dark Kiss Perfume Oil",
    slug: "dark-kiss-perfume-oil",
    description: "Dark berries meet black cherry and soft rose. A forbidden, romantic scent that lingers all day.",
    price: 35,
    category: "body-beauty",
    subcategory: "Perfume Oil",
    image: "/images/products/dark-kiss-perfume-oil.png",
    inStock: true,
    isFeatured: false,
    views: 180,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "crazy-love-perfume-oil",
    name: "Crazy Love Perfume Oil",
    slug: "crazy-love-perfume-oil",
    description: "Passionate and wild. A bold, irresistible blend of red berries, rose, and warm musk.",
    price: 35,
    category: "body-beauty",
    subcategory: "Perfume Oil",
    image: "/images/products/crazy-love-perfume-oil.png",
    inStock: true,
    isFeatured: false,
    views: 165,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ===== BODY & BEAUTY — Serums & Lotions =====
  {
    id: "body-serum-candela",
    name: "Illuminating Body Serum",
    slug: "body-serum-candela",
    description: "A luxurious gold-infused body serum that nourishes, illuminates, and leaves skin with a radiant, dewy glow.",
    price: 85,
    category: "body-beauty",
    subcategory: "Body Serum",
    image: "/images/products/illuminating-body-serum.png",
    inStock: true,
    isFeatured: true,
    views: 480,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "body-lotion-candela",
    name: "Whipped Body Lotion",
    slug: "body-lotion-candela",
    description: "Rich, creamy, and deeply moisturizing. A feminine scented lotion that wraps your skin in softness all day.",
    price: 75,
    category: "body-beauty",
    subcategory: "Body Lotion",
    image: "/images/products/whipped-body-lotion.png",
    inStock: true,
    isFeatured: false,
    views: 220,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ===== CANDLES =====
  {
    id: "vangokh-candle-jar",
    name: "Van Gogh Candle Jar",
    slug: "vangokh-candle-jar",
    description: "Art meets ambiance. The iconic Starry Night by Van Gogh comes alive on this stunning candle jar. 100% natural wax.",
    price: 120,
    category: "candles",
    subcategory: "Candle Jar",
    image: "/images/products/vangokh-candle.png",
    inStock: true,
    isFeatured: true,
    views: 390,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "massage-candle",
    name: "Massage Candle",
    slug: "massage-candle",
    description: "A dual-purpose luxury candle that melts into a warm, nourishing massage oil. Rose, vanilla, and soft musk.",
    price: 95,
    category: "candles",
    subcategory: "Massage Candle",
    image: "/images/products/massage-candle.png",
    inStock: true,
    isFeatured: true,
    views: 310,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "coffee-latte-candle",
    name: "Coffee Latte Candle",
    slug: "coffee-latte-candle",
    description: "Warm roasted espresso, creamy vanilla milk, and caramel drizzle in a glass cup.",
    price: 90,
    category: "candles",
    subcategory: "Candle Jar",
    image: "/images/products/coffee-latte-candle.png",
    inStock: true,
    isFeatured: true,
    views: 270,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "romeo-and-juliet-candle",
    name: "Romeo & Juliet Candle",
    slug: "romeo-and-juliet-candle",
    description: "Sculptural art candle celebrating eternal love. Hand-poured natural soy wax.",
    price: 85,
    category: "candles",
    subcategory: "Candle Jar",
    image: "/images/products/romeo-and-juliet-candle.png",
    inStock: true,
    isFeatured: false,
    views: 190,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ===== HOME & CAR =====
  {
    id: "car-diffuser",
    name: "Luxury Car Diffuser",
    slug: "car-diffuser",
    description: "Transform your drive into a luxury experience. Amber glass diffuser filled with Candela's signature scent.",
    price: 45,
    category: "home-car",
    subcategory: "Car Diffuser",
    image: "/images/products/car-diffuser.png",
    inStock: true,
    isFeatured: true,
    views: 295,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "blue-air-freshener",
    name: "Ocean Breeze Air Freshener",
    slug: "blue-air-freshener",
    description: "Crisp ocean air, sea salt, and white lilies. Fresh scent for your car or home.",
    price: 40,
    category: "home-car",
    subcategory: "Air Freshener",
    image: "/images/products/blue-air-freshener.png",
    inStock: true,
    isFeatured: false,
    views: 140,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "black-air-freshener",
    name: "Velvet Night Air Freshener",
    slug: "black-air-freshener",
    description: "Smoky amber, oud wood, and bergamot for a sophisticated atmosphere.",
    price: 40,
    category: "home-car",
    subcategory: "Air Freshener",
    image: "/images/products/black-air-freshener.png",
    inStock: true,
    isFeatured: false,
    views: 160,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const STATIC_SETTINGS: Record<string, string> = {
  phone: "+20 100 000 0000",
  whatsapp: "+20 100 000 0000",
  store_name: "CANDELA",
  tagline: "Your Feminine Scent",
  about: "CANDELA is a premium feminine fragrance and lifestyle brand crafted for the woman who celebrates herself every day. From luxurious body mists to artisan candles, every product is a sensory experience.",
  instagram: "@candela.official",
  currency: "EGP",
  delivery_note: "We will contact you within 24 hours to confirm your order and arrange delivery.",
};
