export interface StaticProduct {
  id: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  category: string;
  subcategory: string;
  image: string;
  inStock: boolean;
  isFeatured: boolean;
  views: number;
  createdAt: string;
  updatedAt: string;
}

export const STATIC_PRODUCTS: StaticProduct[] = [
  {
    "id": "lavender-body-mist",
    "name": "Lavender Body Mist",
    "slug": "lavender-body-mist",
    "description": "Soothing and serene lavender mist. Perfect for winding down or refreshing throughout the day.",
    "price": 150,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/lavender-body-mist.png",
    "inStock": true,
    "isFeatured": true,
    "views": 74,
    "createdAt": "2026-09-05T13:20:50.456Z",
    "updatedAt": "2026-09-08T18:35:59.095Z"
  },
  {
    "id": "lavender-perfume-oil",
    "name": "Lavender Perfume Oil",
    "slug": "lavender-perfume-oil",
    "description": "Pure, calming lavender with a hint of vanilla and clean musk.",
    "price": 100,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/lavender-perfume-oil.png",
    "inStock": true,
    "isFeatured": true,
    "views": 96,
    "createdAt": "2026-09-05T13:20:50.481Z",
    "updatedAt": "2026-09-08T18:35:42.976Z"
  },
  {
    "id": "baccarat-rouge-body-mist",
    "name": "Baccarat Rouge Body Mist",
    "slug": "baccarat-rouge-body-mist",
    "description": "A luminous and sophisticated fragrance. Radiant, complex, and highly luxurious.",
    "price": 150,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/baccarat-rouge-body-mist.png",
    "inStock": true,
    "isFeatured": true,
    "views": 8,
    "createdAt": "2026-09-05T13:20:50.491Z",
    "updatedAt": "2026-09-08T18:36:09.577Z"
  },
  {
    "id": "whipped-body-lotion",
    "name": "Whipped Body Lotion",
    "slug": "whipped-body-lotion",
    "description": "Indulgent whipped body lotion in a luxury jar. Silky-smooth with a feminine fragrance trail.",
    "price": 200,
    "category": "body-beauty",
    "subcategory": "Body Lotion",
    "image": "/images/products/whipped-body-lotion.png",
    "inStock": true,
    "isFeatured": true,
    "views": 65,
    "createdAt": "2026-09-05T13:20:50.500Z",
    "updatedAt": "2026-09-08T18:36:20.571Z"
  },
  {
    "id": "luxury-body-serum",
    "name": "Luxury Body Serum",
    "slug": "luxury-body-serum",
    "description": "\n\nAn intense illuminating body serum for a deeper, richer glow and profound hydration.",
    "price": 250,
    "category": "body-beauty",
    "subcategory": "Body Serum",
    "image": "/images/products/luxury-body-serum.png",
    "inStock": true,
    "isFeatured": true,
    "views": 1,
    "createdAt": "2026-09-05T13:20:50.517Z",
    "updatedAt": "2026-09-08T18:34:10.879Z"
  },
  {
    "id": "illuminating-body-serum",
    "name": "Illuminating Body Serum",
    "slug": "illuminating-body-serum",
    "description": "A luxurious illuminating body serum that nourishes deeply while leaving your skin with a radiant, golden glow.",
    "price": 250,
    "category": "body-beauty",
    "subcategory": "Body Serum",
    "image": "/images/products/illuminating-body-serum.png",
    "inStock": true,
    "isFeatured": true,
    "views": 44,
    "createdAt": "2026-09-05T13:20:50.529Z",
    "updatedAt": "2026-09-08T18:32:10.476Z"
  },
  {
    "id": "car-diffuser",
    "name": "Car Diffuser",
    "slug": "car-diffuser",
    "description": "A premium car diffuser with an amber stone bead on a rich red cord. Fill your car with your favourite Candela scent.",
    "price": 150,
    "category": "home-car",
    "subcategory": "Car Diffuser",
    "image": "/images/products/car-diffuser.png",
    "inStock": true,
    "isFeatured": true,
    "views": 42,
    "createdAt": "2026-09-05T13:20:50.538Z",
    "updatedAt": "2026-09-08T18:31:53.596Z"
  },
  {
    "id": "crazy-love-perfume-oil",
    "name": "Crazy Love Perfume Oil",
    "slug": "crazy-love-perfume-oil",
    "description": "A passionate floral oriental. Rose, patchouli, and vanilla entwined in a romantic embrace.",
    "price": 100,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/crazy-love-perfume-oil.png",
    "inStock": true,
    "isFeatured": true,
    "views": 71,
    "createdAt": "2026-09-05T13:20:50.549Z",
    "updatedAt": "2026-09-08T18:31:34.727Z"
  },
  {
    "id": "dark-kiss-body-mist",
    "name": "Dark Kiss Body Mist",
    "slug": "dark-kiss-body-mist",
    "description": "Seductive berry and black rose with a warm vanilla musk base. Deeply feminine.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/dark-kiss-body-mist.png",
    "inStock": true,
    "isFeatured": true,
    "views": 35,
    "createdAt": "2026-09-05T13:20:50.559Z",
    "updatedAt": "2026-09-05T13:20:50.559Z"
  },
  {
    "id": "dark-kiss-perfume-oil",
    "name": "Dark Kiss Perfume Oil",
    "slug": "dark-kiss-perfume-oil",
    "description": "Seductive berry and black rose with a warm vanilla musk base in a concentrated oil.",
    "price": 35,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/dark-kiss-perfume-oil.png",
    "inStock": true,
    "isFeatured": false,
    "views": 95,
    "createdAt": "2026-09-05T13:20:50.569Z",
    "updatedAt": "2026-09-05T13:20:50.569Z"
  },
  {
    "id": "gingham-body-mist",
    "name": "Gingham Body Mist",
    "slug": "gingham-body-mist",
    "description": "Clean, fresh and cheerful. Bright citrus notes over a soft floral heart.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/gingham-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 11,
    "createdAt": "2026-09-05T13:20:50.578Z",
    "updatedAt": "2026-09-05T13:20:50.578Z"
  },
  {
    "id": "glazed-donut-body-mist",
    "name": "Glazed Donut Body Mist",
    "slug": "glazed-donut-body-mist",
    "description": "Sweet, warm, and irresistible. A delicious gourmand scent of fresh vanilla and sugar.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/glazed-donut-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 24,
    "createdAt": "2026-09-05T13:20:50.589Z",
    "updatedAt": "2026-09-05T13:20:50.589Z"
  },
  {
    "id": "in-the-stars-body-mist",
    "name": "In The Stars Body Mist",
    "slug": "in-the-stars-body-mist",
    "description": "Celestial and soft. Starlit musk with delicate white floral and warm amber.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/in-the-stars-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 51,
    "createdAt": "2026-09-05T13:20:50.599Z",
    "updatedAt": "2026-09-05T13:20:50.599Z"
  },
  {
    "id": "into-the-night-body-mist",
    "name": "Into The Night Body Mist",
    "slug": "into-the-night-body-mist",
    "description": "A timeless, feminine, alluring blend of dark berries, midnight jasmine and rich amber.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/into-the-night-body-mist.png",
    "inStock": true,
    "isFeatured": true,
    "views": 88,
    "createdAt": "2026-09-05T13:20:50.609Z",
    "updatedAt": "2026-09-05T13:20:50.609Z"
  },
  {
    "id": "kayali-vanilla-body-mist",
    "name": "Kayali Vanilla 28 Body Mist",
    "slug": "kayali-vanilla-body-mist",
    "description": "A rich, decadent vanilla masterpiece. Warm, sweet, and incredibly comforting.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/kayali-vanilla-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 41,
    "createdAt": "2026-09-05T13:20:50.619Z",
    "updatedAt": "2026-09-05T13:20:50.619Z"
  },
  {
    "id": "khomra-body-mist",
    "name": "Khomra Body Mist",
    "slug": "khomra-body-mist",
    "description": "A deeply luxurious and enchanting oriental fragrance with warm spices and amber.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/khomra-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 70,
    "createdAt": "2026-09-05T13:20:50.629Z",
    "updatedAt": "2026-09-05T13:20:50.629Z"
  },
  {
    "id": "massage-candle",
    "name": "Massage Candle",
    "slug": "massage-candle",
    "description": "A luxurious dual-purpose candle that melts into a warm, nourishing massage oil. Romance meets self-care.",
    "price": 95,
    "category": "candles",
    "subcategory": "Massage Candle",
    "image": "/images/products/massage-candle.png",
    "inStock": true,
    "isFeatured": true,
    "views": 91,
    "createdAt": "2026-09-05T13:20:50.638Z",
    "updatedAt": "2026-09-05T13:20:50.638Z"
  },
  {
    "id": "scandal-perfume-oil",
    "name": "Scandal Perfume Oil",
    "slug": "scandal-perfume-oil",
    "description": "Bold, seductive, unforgettable. A feminine oriental scent with honey, mandarin, and caramel.",
    "price": 35,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/scandal-perfume-oil.png",
    "inStock": true,
    "isFeatured": true,
    "views": 65,
    "createdAt": "2026-09-05T13:20:50.646Z",
    "updatedAt": "2026-09-05T13:20:50.646Z"
  },
  {
    "id": "thousand-wishes-perfume-oil",
    "name": "Thousand Wishes Perfume Oil",
    "slug": "thousand-wishes-perfume-oil",
    "description": "Warm sparkling champagne, almond blossom, and sandalwood. A celebration in a bottle.",
    "price": 35,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/thousand-wishes-perfume-oil.png",
    "inStock": true,
    "isFeatured": false,
    "views": 40,
    "createdAt": "2026-09-05T13:20:50.656Z",
    "updatedAt": "2026-09-05T13:20:50.656Z"
  },
  {
    "id": "yara-candy-body-mist",
    "name": "Yara Candy Body Mist",
    "slug": "yara-candy-body-mist",
    "description": "Playful, sweet, and wildly feminine. A sugary candy delight.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/yara-candy-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 49,
    "createdAt": "2026-09-05T13:20:50.670Z",
    "updatedAt": "2026-09-05T13:20:50.670Z"
  },
  {
    "id": "van-gogh-candle-jar",
    "name": "Van Gogh Candle Jar",
    "slug": "van-gogh-candle-jar",
    "description": "An artistic candle jar featuring a Van Gogh Starry Night inspired label.",
    "price": 250,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/vangogh-candle.png",
    "inStock": true,
    "isFeatured": true,
    "views": 52,
    "createdAt": "2026-09-05T13:20:50.683Z",
    "updatedAt": "2026-09-08T18:31:13.148Z"
  },
  {
    "id": "gingham-candle",
    "name": "Gingham Candle",
    "slug": "gingham-candle",
    "description": "500 gram \nFresh and cheerful blue gingham candle to brighten any room. ",
    "price": 600,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/gingham-candle.png",
    "inStock": true,
    "isFeatured": true,
    "views": 52,
    "createdAt": "2026-09-05T13:20:50.695Z",
    "updatedAt": "2026-09-08T18:30:50.122Z"
  },
  {
    "id": "black-air-freshener",
    "name": "Black Air Freshener",
    "slug": "black-air-freshener",
    "description": "A sophisticated and bold air freshener for your car or home.",
    "price": 45,
    "category": "home-car",
    "subcategory": "Air Freshener",
    "image": "/images/products/black-air-freshener.png",
    "inStock": true,
    "isFeatured": false,
    "views": 50,
    "createdAt": "2026-09-06T01:44:07.517Z",
    "updatedAt": "2026-09-06T01:44:07.517Z"
  },
  {
    "id": "blue-air-freshener",
    "name": "Blue Air Freshener",
    "slug": "blue-air-freshener",
    "description": "A crisp, clean, and refreshing blue air freshener.",
    "price": 45,
    "category": "home-car",
    "subcategory": "Air Freshener",
    "image": "/images/products/blue-air-freshener.png",
    "inStock": true,
    "isFeatured": false,
    "views": 84,
    "createdAt": "2026-09-06T01:44:07.537Z",
    "updatedAt": "2026-09-06T01:44:07.537Z"
  },
  {
    "id": "yellow-air-freshener",
    "name": "Yellow Air Freshener",
    "slug": "yellow-air-freshener",
    "description": "A bright, sunny, and uplifting citrus air freshener.",
    "price": 45,
    "category": "home-car",
    "subcategory": "Air Freshener",
    "image": "/images/products/yellow-air-freshener.png",
    "inStock": true,
    "isFeatured": false,
    "views": 6,
    "createdAt": "2026-09-06T01:44:07.554Z",
    "updatedAt": "2026-09-06T01:44:07.554Z"
  },
  {
    "id": "bloom-girl-candle",
    "name": "Bloom Girl Candle",
    "slug": "bloom-girl-candle",
    "description": "A beautifully crafted floral candle that brings a garden of blooming flowers into your space.",
    "price": 110,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/bloom-girl-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 27,
    "createdAt": "2026-09-06T01:44:07.574Z",
    "updatedAt": "2026-09-06T01:44:07.574Z"
  },
  {
    "id": "classic-candle-1",
    "name": "Classic Candle",
    "slug": "classic-candle-1",
    "description": "An elegant, classic Candela jar candle with a timeless scent.",
    "price": 95,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/classic-candle-1.png",
    "inStock": true,
    "isFeatured": false,
    "views": 75,
    "createdAt": "2026-09-06T01:44:07.592Z",
    "updatedAt": "2026-09-06T01:44:07.592Z"
  },
  {
    "id": "coffee-latte-candle",
    "name": "Coffee Latte Candle",
    "slug": "coffee-latte-candle",
    "description": "A deliciously scented candle that looks and smells like a fresh, warm coffee latte. A perfect dessert candle.",
    "price": 130,
    "category": "candles",
    "subcategory": "Candle Cakes",
    "image": "/images/products/coffee-latte-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 32,
    "createdAt": "2026-09-06T01:44:07.605Z",
    "updatedAt": "2026-09-06T01:44:07.605Z"
  },
  {
    "id": "couples-candle",
    "name": "Couples Romance Candle",
    "slug": "couples-candle",
    "description": "A deeply romantic candle designed to set the perfect mood for couples.",
    "price": 120,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/couples-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 77,
    "createdAt": "2026-09-06T01:44:07.619Z",
    "updatedAt": "2026-09-06T01:44:07.619Z"
  },
  {
    "id": "peony-blossom-candle",
    "name": "Peony Blossom Candle",
    "slug": "peony-blossom-candle",
    "description": "A delicate and luxurious peony-scented candle that fills the room with soft floral notes.",
    "price": 100,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/peony-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 30,
    "createdAt": "2026-09-06T01:44:07.632Z",
    "updatedAt": "2026-09-08T18:37:58.040Z"
  },
  {
    "id": "pink-candle",
    "name": "Pink Velvet Candle",
    "slug": "pink-candle",
    "description": "Our signature soft pink candle. Feminine, warm, and comforting.",
    "price": 105,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/pink-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 10,
    "createdAt": "2026-09-06T01:44:07.646Z",
    "updatedAt": "2026-09-06T01:44:07.646Z"
  },
  {
    "id": "romeo-candle",
    "name": "Romeo Candle",
    "slug": "romeo-candle",
    "description": "A strong, captivating, and romantic fragrance encapsulated in an elegant jar.",
    "price": 120,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/romeo-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 85,
    "createdAt": "2026-09-06T01:44:07.658Z",
    "updatedAt": "2026-09-06T01:44:07.658Z"
  },
  {
    "id": "romeo-and-juliet-candle",
    "name": "Romeo & Juliet Candle",
    "slug": "romeo-and-juliet-candle",
    "description": "The ultimate symbol of romance. A beautifully harmonious scent combining masculine and feminine notes.",
    "price": 140,
    "category": "candles",
    "subcategory": "Candle Jar",
    "image": "/images/products/romeo-and-juliet-candle.png",
    "inStock": true,
    "isFeatured": false,
    "views": 28,
    "createdAt": "2026-09-06T01:44:07.672Z",
    "updatedAt": "2026-09-06T01:44:07.672Z"
  },
  {
    "id": "gingham-perfume-oil",
    "name": "Gingham Perfume Oil",
    "slug": "gingham-perfume-oil",
    "description": "A highly concentrated version of the fresh and cheerful Gingham scent. Bright citrus over soft florals.",
    "price": 100,
    "category": "body-beauty",
    "subcategory": "Perfume Oil",
    "image": "/images/products/gingham-perfume-oil.png",
    "inStock": true,
    "isFeatured": false,
    "views": 82,
    "createdAt": "2026-09-06T01:44:07.685Z",
    "updatedAt": "2026-09-08T18:36:52.286Z"
  },
  {
    "id": "good-girl-gift-set",
    "name": "Good Girl Gift Set",
    "slug": "good-girl-gift-set",
    "description": "The ultimate Good Girl experience. A stunning gift set featuring both the mist and oil.",
    "price": 145,
    "category": "body-beauty",
    "subcategory": "Gift Set",
    "image": "/images/products/good-girl-gift-set.png",
    "inStock": false,
    "isFeatured": false,
    "views": 20,
    "createdAt": "2026-09-06T01:44:07.700Z",
    "updatedAt": "2026-09-08T18:37:08.754Z"
  },
  {
    "id": "loose-highlighter",
    "name": "Loose Highlighter Powder",
    "slug": "loose-highlighter",
    "description": "A finely milled, ultra-reflective loose highlighter that gives your face and body a mesmerizing glow.",
    "price": 85,
    "category": "body-beauty",
    "subcategory": "Highlighter",
    "image": "/images/products/loose-highlighter.png",
    "inStock": true,
    "isFeatured": false,
    "views": 59,
    "createdAt": "2026-09-06T01:44:07.714Z",
    "updatedAt": "2026-09-06T01:44:07.714Z"
  },
  {
    "id": "victoria-secret-inspired-mist",
    "name": "Victoria Secret Inspired Mist",
    "slug": "victoria-secret-inspired-mist",
    "description": "A classic, iconic, and deeply alluring feminine body mist.",
    "price": 150,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/victorias-secret-inspired-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 96,
    "createdAt": "2026-09-06T01:44:07.746Z",
    "updatedAt": "2026-09-08T18:36:38.579Z"
  },
  {
    "id": "angel-pink-body-mist",
    "name": "Angel Pink Body Mist",
    "slug": "angel-pink-body-mist",
    "description": "A soft, heavenly pink mist with angelic floral and sweet notes.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/angel-pink-body-mist.png",
    "inStock": true,
    "isFeatured": true,
    "views": 70,
    "createdAt": "2026-09-06T01:44:07.759Z",
    "updatedAt": "2026-09-06T01:44:07.759Z"
  },
  {
    "id": "bunny-kiss-body-mist",
    "name": "Bunny Kiss Body Mist",
    "slug": "bunny-kiss-body-mist",
    "description": "A playful, sweet, and soft body mist that leaves a gentle lingering scent.",
    "price": 55,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/bunny-kiss-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 50,
    "createdAt": "2026-09-06T01:45:12.311Z",
    "updatedAt": "2026-09-06T01:45:12.311Z"
  },
  {
    "id": "thousand-wishes-body-mist",
    "name": "Thousand Wishes Body Mist",
    "slug": "thousand-wishes-body-mist",
    "description": "Sprays with a beautiful scent",
    "price": 150,
    "category": "body-beauty",
    "subcategory": "Body Mist",
    "image": "/images/products/thousand-wishes-body-mist.png",
    "inStock": true,
    "isFeatured": false,
    "views": 100,
    "createdAt": "2026-09-08T01:13:21.873Z",
    "updatedAt": "2026-09-08T18:35:20.480Z"
  }
];

export const STATIC_SETTINGS: Record<string, string> = {
  "phone": "+20 100 000 0000",
  "whatsapp": "+20 100 000 0000",
  "store_name": "CANDELA",
  "tagline": "Your Feminine Scent",
  "about": "CANDELA is a premium feminine fragrance and lifestyle brand crafted for the woman who celebrates herself every day. From luxurious body mists to artisan candles, every product is a sensory experience.",
  "instagram": "@candela.official",
  "currency": "EGP",
  "delivery_note": "We will contact you within 24 hours to confirm your order and arrange delivery."
};
